[battery]
disabled = true

[character]
success_symbol = '[;](bold green)'
error_symbol = '[;](bold red)'

[container]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false

[pulumi]
disabled = true

[aws]
format = '[$symbol$profile/$region]($style) '
